2025-07-11 11:43:24,474 INFO    MainThread:2057396 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/qrbao/Documents/code4/rllib/mycode/wandb/run-20250711_114324-igwwr1qv/logs/debug.log
2025-07-11 11:43:24,474 INFO    MainThread:2057396 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/qrbao/Documents/code4/rllib/mycode/wandb/run-20250711_114324-igwwr1qv/logs/debug-internal.log
2025-07-11 11:43:24,474 INFO    MainThread:2057396 [wandb_init.py:init():831] calling init triggers
2025-07-11 11:43:24,474 INFO    MainThread:2057396 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'algo': 'PPO', 'enable_new_api_stack': True, 'framework': 'torch', 'env': None, 'num_env_runners': None, 'num_envs_per_env_runner': None, 'num_agents': 4, 'evaluation_num_env_runners': 0, 'evaluation_interval': 0, 'evaluation_duration': 10, 'evaluation_duration_unit': 'episodes', 'evaluation_parallel_to_training': False, 'output': None, 'log_level': None, 'no_tune': False, 'num_samples': 1, 'max_concurrent_trials': None, 'verbose': 2, 'checkpoint_freq': 1, 'checkpoint_at_end': True, 'wandb_key': 'fdd7656f474bba144dea1887bcdab534bc7df647', 'wandb_project': 'waterworld-v4', 'wandb_run_name': None, 'stop_reward': 200.0, 'stop_iters': 200, 'stop_timesteps': 1000000, 'as_test': False, 'as_release_test': False, 'num_learners': None, 'num_cpus_per_learner': None, 'num_gpus_per_learner': None, 'num_aggregator_actors_per_learner': None, 'num_cpus': 0, 'local_mode': False, 'num_gpus': None, 'n_predators': 2, 'n_preys': 2, 'use_onnx_for_inference': False, 'explore_during_inference': False, 'num_episodes_during_inference': 10, '_wandb': {}}
2025-07-11 11:43:26,103 INFO    MainThread:2057396 [wandb_init.py:init():872] starting backend
2025-07-11 11:43:26,103 INFO    MainThread:2057396 [wandb_init.py:init():875] sending inform_init request
2025-07-11 11:43:26,104 INFO    MainThread:2057396 [wandb_init.py:init():883] backend started and connected
2025-07-11 11:43:26,105 INFO    MainThread:2057396 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2025-07-11 11:43:26,109 INFO    MainThread:2057396 [wandb_init.py:init():956] updated telemetry
2025-07-11 11:43:26,111 INFO    MainThread:2057396 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-07-11 11:43:26,841 INFO    MainThread:2057396 [wandb_init.py:init():1032] starting run threads in backend
2025-07-11 11:43:26,906 INFO    MainThread:2057396 [wandb_run.py:_console_start():2453] atexit reg
2025-07-11 11:43:26,906 INFO    MainThread:2057396 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-07-11 11:43:26,906 INFO    MainThread:2057396 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-07-11 11:43:26,906 INFO    MainThread:2057396 [wandb_run.py:_redirect():2393] Redirects installed.
2025-07-11 11:43:26,906 INFO    MainThread:2057396 [wandb_init.py:init():1078] run started, returning control to user process
2025-07-11 17:34:30,170 WARNING MsgRouterThr:2057396 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/qrbao/anaconda3/envs/rllib/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/qrbao/anaconda3/envs/rllib/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/qrbao/anaconda3/envs/rllib/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/qrbao/anaconda3/envs/rllib/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/qrbao/anaconda3/envs/rllib/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-11 17:34:30,171 INFO    MsgRouterThr:2057396 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
